# Main configuration file for the OracleNet project

# General project settings (example)
project_name: "OracleNet"
version: "0.1.0"

################################################################################
# GNN Data Preparation Specific Settings (used by prepare_gnn_data.py)
################################################################################
prepare_gnn_data:
  # Path to the processed OQMD CSV file, input for GNN graph creation
  processed_oqmd_csv_filename: "data/oqmd_processed.csv" # Using the test CSV

  # Paths for the output graph files from prepare_gnn_data.py
  processed_graphs_filename: "data/test_processed_graphs.pt"
  train_graphs_filename: "data/test_train_graphs.pt"
  val_graphs_filename: "data/test_val_graphs.pt"
  test_graphs_filename: "data/test_test_graphs.pt"

  # Data split ratios and random seed for prepare_gnn_data.py
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2 # Sums to 1.0
  random_seed: 42

################################################################################
# Data Preparation Settings (Original - kept for reference, but prepare_gnn_data overrides for the script)
################################################################################
data_preparation:
  input_csv_path: "data/material_data.csv"
  output_graphs_path: "data/all_graphs.pt"
  target_properties:
    - "band_gap"
    - "formation_energy_per_atom"
  max_neighbors: 12
  cutoff_radius: 3.5 # Angstroms
  material_id_column: "material_id"
  data_split:
    train_ratio: 0.8
    val_ratio: 0.1
    test_ratio: 0.1
    random_seed: 42
    train_graphs_path: "data/train_graphs.pt"
    val_graphs_path: "data/val_graphs.pt"
    test_graphs_path: "data/test_graphs.pt"

################################################################################
# OracleNet GNN Model Settings
################################################################################
gnn_settings:
  train_graphs_path: "data/test_train_graphs.pt" # Align with test output
  val_graphs_path: "data/test_val_graphs.pt"     # Align with test output
  test_graphs_path: "data/test_test_graphs.pt"   # Align with test output
  model_save_path: "data/oracle_net_gnn_test.pth"
  learning_rate: 0.001
  batch_size: 4 # Smaller for potentially small test dataset
  epochs: 10    # Smaller for testing
  hidden_channels: 16
  target_index: 0
  num_node_features_for_dummy_data: 2
  num_targets_in_file_for_dummy_data: 2

# End of config.yml
